# Generated by Django 4.2 on 2023-04-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField(max_length=15, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.city')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateField(auto_now_add=True)),
                ('mission_objective', models.TextField(max_length=500)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=255)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=255)),
                ('sector_description', models.CharField(max_length=255, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester_begin', models.DateField()),
                ('trimester_end', models.DateField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.FloatField(default=0.0)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.company')),
                ('trimester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.trimester')),
            ],
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.company')),
            ],
        ),
        migrations.CreateModel(
            name='Inspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('inspection_report', models.TextField(max_length=500)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agent')),
                ('mission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.province')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sector'),
        ),
        migrations.AddField(
            model_name='city',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.department'),
        ),
    ]
