# Generated by Django 4.2 on 2023-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_agent_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='sector_id',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='province_id',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='inspect',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='inspect',
            old_name='mission_id',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='localization',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='trimester_id',
            new_name='trimester',
        ),
    ]
