# Generated by Django 4.2 on 2023-05-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_order_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspect',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.agent'),
        ),
        migrations.CreateModel(
            name='InspectionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('inspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inspect')),
                ('inspection_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inspectionquestion')),
            ],
        ),
    ]
