# Generated by Django 4.2 on 2023-05-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_mission_mission_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAppointedMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agent')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mission')),
            ],
        ),
    ]
