# Generated by Django 4.2 on 2023-05-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_mission_mission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAppointedMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.company')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mission')),
            ],
        ),
    ]
