# Generated by Django 4.2 on 2023-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_payment_payment_number_alter_payment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100)),
                ('filetype', models.CharField(blank=True, max_length=10)),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
