# Generated by Django 4.2 on 2023-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_inspect_inspection_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspect',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
