# Generated by Django 4.2 on 2023-06-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_inspect_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('selectedValue', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('inspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inspect')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.question')),
            ],
        ),
        migrations.DeleteModel(
            name='InspectionAnswer',
        ),
        migrations.DeleteModel(
            name='InspectionQuestion',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.question'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.contact'),
        ),
    ]
