# Generated by Django 4.2 on 2023-07-16 08:18

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_alter_user_role_agentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.user',),
            managers=[
                ('agent', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
