# Generated by Django 4.2 on 2023-07-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_agentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='agent_id',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='firstname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='lastname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='registration_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
