# Generated by Django 4.2 on 2023-07-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_remove_agentprofile_agent_id_agentprofile_create_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='create_on',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='agent_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.agent'),
        ),
    ]
