# Generated by Django 4.2 on 2023-07-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_remove_agentprofile_create_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='agent_id',
            new_name='agent',
        ),
    ]
