# Generated by Django 4.2 on 2023-07-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_rename_agent_id_agentprofile_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.agent'),
        ),
    ]
