# Generated by Django 4.2 on 2023-07-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_agentprofile_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantprofile',
            name='accountant_id',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.agent'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.agent'),
        ),
    ]
