# Generated by Django 4.2 on 2023-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_remove_accountantprofile_accountant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
